// style file for icon which were generated by https://icomoon.io. Now just have 6 icon
import './style.css'

import Vue from 'vue'
import VueAudio from './VueAudio.vue'

const Audio = new Vue({
  el: '#audio',
  components: {
    VueAudio
  }
})
